Traceback (most recent call last):
  File "/gscratch/stf/lbc800/fashion-app/train_attribute_detector.py", line 175, in <module>
    train_loader = DataLoader(training_data, batch_size= batch_size, shuffle=True, num_workers= 6)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 383, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 164, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 173, in num_samples
    return len(self.data_source)
  File "/gscratch/stf/lbc800/fashion-app/train_attribute_detector.py", line 42, in __len__
    return len(self.image_paths)
AttributeError: 'CustomDataset' object has no attribute 'image_paths'
